<a href="https://colab.research.google.com/github/sungwon3615-cloud/Linear_Algebra/blob/main/%EC%8B%A4%EC%8A%B5zero.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello world")
x = 3

Hello world


## 파이썬 기초

In [ ]:
# integer
x = 3
print ("정수: %01d, %02d, %03d, %04d %05d" % (x,x,x,x,x))

#float
x = 256.123
print ("실수: %.0f, %.1f, %.2f" % (x,x,x))

#string
x = "Hello, World"
print("문자열: [%s]" % (x))



정수: 3, 03, 003, 0003 00003
실수: 256, 256.1, 256.12
문자열: [Hello, World]


In [ ]:
contents =["Regression", "Classification", "SVM", "Clustering", "Dimension reduction", "NN", "CNN", "AE", "GAN", "RNN"]
for con in contents:
  if con in ["Regression", "Classification", "SVM", "Clustering", "Dimension reduction"]:
    print("%s 은(는) 기계학습내용입니다." %con)
  elif con in ["CNN"]:
    print("%s 은(는) convoltational." %con)
  else:
    print("%s 은(는) 심층학습 내용입니다." %con)

for(i,con) in enumerate(contents):
    print("[%d/%d]: %s" %(i, len(contents), con))

Regression 은(는) 기계학습내용입니다.
Classification 은(는) 기계학습내용입니다.
SVM 은(는) 기계학습내용입니다.
Clustering 은(는) 기계학습내용입니다.
Dimension reduction 은(는) 기계학습내용입니다.
NN 은(는) 심층학습 내용입니다.
CNN 은(는) convoltational.
AE 은(는) 심층학습 내용입니다.
GAN 은(는) 심층학습 내용입니다.
RNN 은(는) 심층학습 내용입니다.
[0/10]: Regression
[1/10]: Classification
[2/10]: SVM
[3/10]: Clustering
[4/10]: Dimension reduction
[5/10]: NN
[6/10]: CNN
[7/10]: AE
[8/10]: GAN
[9/10]: RNN


In [ ]:
def sum(a,b):
  return a+b

x=  10.0
y = 20.0
print("%.1f + %.1f = %.1f" %(x, y, sum(x,y)))

10.0 + 20.0 = 30.0


In [ ]:
a =[]
b =[1, 2, 3]
c =["Hello", "," "wolrd"]
d=[1, 2, 3, "x", "y", "z"]
x=[]
print(x)

x.append('a')
print(x)

x.append(123)
print(x)

x.append(["a", "b"])
print(x)



[]
['a']
['a', 123]
['a', 123, ['a', 'b']]


In [ ]:
dic = dict()
dic["name"] = "Heekyung"
dic["town"] = "Goyang"
dic["jab"] = "Assistant professor"
print(dic)

{'name': 'Heekyung', 'town': 'Goyang', 'jab': 'Assistant professor'}


In [ ]:
class Student:
  #생성자
  def __init__(self, name):
    self.name = name
  #메서드
  def study(self, hard = False):
    if hard:
      print("%s 학생은 열심히 공부를 합니다." %self.name)
    else:
      print("%s 학생은 공부를 합니다." %self.name)

s = Student("Heekyung")
s.study()
s.study(hard=True)



Heekyung 학생은 공부를 합니다.
Heekyung 학생은 열심히 공부를 합니다.


##백터 행렬 연산 그래프 그리기



In [12]:
import numpy as np

def print_val(x):
  print ("Type:", type(x))
  print ("Shape:", x.shape)
  print ("값:\n", x)
  print (" ")

x = np.array([1,2,3])
print_val(x)

x[0] = 5
print_val(x)

y = np.array([[1,2,3], [4,5,6]])
print_val(y)

a = np.ones((3,2))
print_val(a)

a = np.zeros((2,2))
print_val(a)

a = np.eye(3,3)
print_val(a)

a = np.random.random((4,4))
print_val(a)

a = np.random.randn(4,4)
print_val(a)

a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print_val(a)

b = a[:2, 1:3] # 행 0~1 열 1~2
print_val(b)

row1 = a[1, :]
print_val(row1)

m1 = np.array([[1,2], [3,4]])
m2 = np.array([[5,6], [7,8]])
print_val(m1+m2)
print_val(np.add(m1,m2))

print_val(m1 -m2)
print_val(np.subtract(m1, m2))

print_val(m1 *m2)
print_val(np.multiply(m1, m2))



Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [1 2 3]
 
Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [5 2 3]
 
Type: <class 'numpy.ndarray'>
Shape: (2, 3)
값:
 [[1 2 3]
 [4 5 6]]
 
Type: <class 'numpy.ndarray'>
Shape: (3, 2)
값:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
 
Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값:
 [[0. 0.]
 [0. 0.]]
 
Type: <class 'numpy.ndarray'>
Shape: (3, 3)
값:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값:
 [[0.05842049 0.05402056 0.15044271 0.0283282 ]
 [0.91879053 0.3963209  0.28988508 0.22546935]
 [0.18003069 0.29734564 0.14982163 0.66229922]
 [0.67828199 0.33495699 0.62395687 0.08441821]]
 
Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값:
 [[-0.58259395  0.15499206 -0.64878653 -0.00164834]
 [ 0.62974882  1.39722755 -1.1366725   0.36614916]
 [ 0.79963081  0.49047216  0.49295016 -0.43316846]
 [-1.40655091 -0.33121125 -1.12559591 -0.71926746]]
 
Type: <class 'numpy.ndarray'>
Shape: (3, 4)
값:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12